services:
  handler:
    build:
      context: .
      dockerfile: handler.Dockerfile
    environment:
      YT_DOWNLOADER_PATH: ./downloads
      REDIS_HOSTNAME: redis
      QUEUE_NAME: YT_DOWNLOADER_QUEUE
    ports:
      - "5000:5000"
    depends_on:
      - redis
  worker:
    user: 0:0
    build:
      context: .
      dockerfile: worker.Dockerfile
    environment:
      YT_DOWNLOADER_PATH: ./downloads
      REDIS_HOSTNAME: redis
      QUEUE_NAME: YT_DOWNLOADER_QUEUE
      FFMPEG_GLOBAL_FLAGS: ${FFMPEG_GLOBAL_FLAGS}
      MAX_PROCESS_WORKERS: ${MAX_PROCESS_WORKERS:-4}
    depends_on:
      - redis
    volumes:
      - ${OUTPUT_FILE_PATH}:/usr/src/app/downloads
  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"